### ISSUE TITLE
CMake Policy CMP0128 Warnings in Dependencies During Build Process

### ISSUE THREAD

**Issue by altunenes** [thewh1teagle/sherpa-rs#4]
When building the project, multiple warnings are generated related to CMake policies not being set. These warnings occur across several dependencies. The details of the warnings are provided below.
Note I have started to see those after 0.1.5 update

OS: Win11 latest

```
This warning is for project developers.  Use -Wno-dev to suppress it.

Called from: [1] C:/Users/enes-/OneDrive/Masaüstü/sherpa-rs/target/debug/build/sherpa-rs-sys-1fafd78e6aee6374/out/build/_deps/eigen-src/blas/CMakeLists.txt
CMake Warning (dev) in C:/Users/enes-/OneDrive/Masaüstü/sherpa-rs/target/debug/build/sherpa-rs-sys-1fafd78e6aee6374/out/build/_deps/eigen-src/blas/CMakeLists.txt:
  Policy CMP0128 is not set: Selection of language standard and extension
  flags improved.  Run "cmake --help-policy CMP0128" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, compiler extensions won't
  be enabled.
This warning is for project developers.  Use -Wno-dev to suppress it.

...

CMake Warning (dev) in C:/Users/enes-/OneDrive/Masaüstü/sherpa-rs/target/debug/build/sherpa-rs-sys-1fafd78e6aee6374/out/build/_deps/portaudio-src/CMakeLists.txt:
  Policy CMP0128 is not set: Selection of language standard and extension
  flags improved.  Run "cmake --help-policy CMP0128" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

  For compatibility with older versions of CMake, compiler extensions won't
  be enabled.
This warning is for project developers.  Use -Wno-dev to suppress it.

...

CMake Warning (dev) in C:/Users/enes-/OneDrive/Masaüstü/sherpa-rs/target/debug/build/sherpa-rs-sys-1fafd78e6aee6374/out/build/_deps/espeak_ng-src/CMakeLists.txt:
  Policy CMP0082 is not set: Install rules from add_subdirectory() are
  interleaved with those in caller.  Run "cmake --help-policy CMP0082" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

  build script failed, must exit now
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: cmake::find_exe::{{closure}}
     3: <cmake::Version as core::default::Default>::default
     4: cmake::Config::build
     5: std::ffi::os_str::OsString::new
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
...

```

**Comment by thewh1teagle** [comment]
Thanks for report :)
What's the version of your cmake? Can you try to update it from https://cmake.org/download/
Just to understand, it only shows warning but compiles successfully?

**Comment by altunenes** [comment]
It was both. :-)  I updated CMake, but I could clearly see that both build errors and warnings persisted.

```
cmake --version
cmake version 3.30.0
```

Then I tried this, and the build errors disappeared, so it actually works now (all examples compile without any error), but I still have those warnings:

```
cargo clean
cargo build
```

Note: I'm not sure if updating CMake fixed my error or if it was the cargo clean/build process sorry for the bad testing pipeline lol.

```
  CMake Warning (dev) at sherpa-onnx/c-api/CMakeLists.txt:2 (add_library):
    Policy CMP0156 is not set: De-duplicate libraries on link lines based on
    linker capabilities.  Run "cmake --help-policy CMP0156" for policy details.
    Use the cmake_policy command to set the policy and suppress this warning.
    Since the policy is not set, legacy libraries de-duplication strategy will
    be applied.
  This warning is for project developers.  Use -Wno-dev to suppress it.
     Called from: [1]	C:/Users/enes-/OneDrive/Masaüstü/sherpa-rs/target/debug/build/sherpa-rs-sys-a72352a1a84f7e76/out/sherpa-onnx/sherpa-onnx/c-api/CMakeLists.txt
  thread 'main' panicked at C:\Users\enes-\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:
  command did not execute successfully, got: exit code: 1
  build script failed, must exit now
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\std\src\panicking.rs:652
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library\core\src\panicking.rs:72
     2: cmake::find_exe::{{closure}}
     3: <cmake::Version as core::default::Default>::default
     4: cmake::Config::build
     5: <T as core::convert::Into<U>>::into
     6: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I'm closing the issue since it currently works, but I will update this if I can fix those persistent warnings.

**Comment by altunenes** [comment]
build warnings are gone with
`sherpa-rs = "=0.1.7-beta.0"`
